label: Buttons
status: wip
collated: true
default: primary
preview: '@uswds-framed'
order: 6

variants:
  - name: primary
    context:
      category: primary
      label: Primary buttons
      classes: 'usa-button'

  - name: primary-alt
    context:
      category: primary
      label: Primary alt buttons
      classes: 'usa-button-primary-alt'

  - name: secondary
    context:
      category: secondary
      label: Secondary buttons
      classes: 'usa-button-secondary'

  - name: outline
    context:
      category: secondary
      label: Outline buttons
      classes: 'usa-button-outline'

  - name: focus
    context:
      category: focus
      label: Button focus
      classes: 'usa-button-focus'

  - name: disabled
    context:
      category: 'disabled'
      label: Disabled button
      classes: 'usa-button-disabled'

  - name: big
    context:
      category: 'big'
      label: Big button
      classes: 'usa-button-big'
