version: '3'
services:
  vets-website:
    image: vets-website:${IMAGE_TAG:-latest}
    build:
      context: .
    volumes:
      - .:/application
    environment:
      WEB_HOST: 'vets-website'
      WEB_PORT: 3001
      API_HOST: 'vets-website'
    expose:
      - 3001
      - 3000
    command: ./script/run-docker-nightwatch.sh
  selenium-chrome:
    image: selenium/standalone-chrome
    links:
      - vets-website
    shm_size: 2g
    expose:
      - 4444
    environment:
      GRID_BROWSER_TIMEOUT: 10000
      GRID_TIMEOUT: 12000
      DBUS_SESSION_BUS_ADDRESS: /dev/null
