# note: this GHA applies only to Github Projects Beta
# docs: https://github.com/actions/add-to-project ?
name: Add issues to Github Beta projects

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add Platform Leadership issue to project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/623/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: platform-leadership
