name: set po-sync flag

on:
  issues:
    types:
      - labeled

jobs:
  do-sync:
    name: Create Completed Ticket
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'CC-Request') &&
        (github.event.label.name == 'PO-Sync-approved'}}
    steps:
    - name: Get data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: ${{ github.repository_owner }}
        PROJECT_NUMBER: 998
        LABEL_CHECK: "VFS Team"

      run: |
        PROJECT_ID=$(gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f org=$ORGANIZATION -f number=$PROJECT_NUMBER --jq '.data.organization.projectV2.id')
        
        echo "The Project ID is...$PROJECT_ID"